spring.data.mongodb.uri=mongodb+srv://martinxdddd:Sasa.1234@cl-distribuidora-1.cto3viu.mongodb.net/?retryWrites=true&w=majority&appName=cl-distribuidora-1
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.data.mongodb.database=cl-distribuidora-1
